### ISSUE TITLE
1.8 Bug

### ISSUE THREAD

**Issue by notfoundname** [Misat11/BedWars#18]
This bug is happening after setuping an arena and reloading my server (/stop).
Spigot version: 1.8 
BedWars version: 0.1.1

Plugins (9): MultiWorld, WorldEdit, NFNPlugin, PlaceholderAPI, ProtocolLib, Sunny, BedWars, ChestCommands, DeluxeMenus

Error occurred while enabling BedWars v0.1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/boss/BarColor
        at misat11.bw.game.Game.loadBossBarColor(Game.java:764) ~[?:?]
        at misat11.bw.game.Game.loadGame(Game.java:743) ~[?:?]
        at misat11.bw.Main.onEnable(Main.java:443) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: org.bukkit.boss.BarColor
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 14 more

Here's configs
[BedWars.zip](https://github.com/Misat11/BedWars/files/3221739/BedWars.zip)

**Comment by Misat11** [comment]
Use latest development version from jenkins or wait for new release.
