### ISSUE TITLE
NPE/ Sand Bug

### ISSUE THREAD

**Issue by Boy132** [Misat11/BedWars#22]
I created a game, restarted the server. Now I wanted to edit the game and save it and when typing the save command the errror appears.

**Server and plugin version**
Spigot version: 1.13.2
BedWars version: 0.1.4

**Installed plugins on server (can be obtained by `/pl`):**
BedWars, WorldGuard, WorldEdit, Multiverse

**Console log:**
[16:31:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin BedWars v0.1.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-1a3504a-84f3da3]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at misat11.bw.game.Game.saveToConfig(Game.java:872) ~[?:?]
at misat11.bw.game.GameCreator.cmd(GameCreator.java:202) ~[?:?]
at misat11.bw.commands.BwCommand.onCommand(BwCommand.java:538) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
... 15 more

**Comment by Boy132** [comment]
After I reload the plugin (/bw reload) the game works again,
It seems that the plugin is loaded before the world?

**Comment by Misat11** [comment]
Yes, the plugin is loaded before world, so try to autoload this world (Multiverse can do this)

**Comment by Boy132** [comment]
Maybe you could add a option that the plugin loads the worlds of the arenas?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 25.06.19, 19:00, Misat11 <notifications@github.com> schrieb:
Yes, the plugin is loaded before world, so try to autoload this world (Multiverse can do this)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Misat11** [comment]
try to use new version from jenkins

**Comment by Boy132** [comment]
That fixed that problem but now sand isn't falling anymore... I tested it and it's definitely this addon. :/

**Comment by Boy132** [comment]
The bug still persists.

**Comment by Misat11** [comment]
try new build

**Comment by Boy132** [comment]
It works now!
Thanks for the quick support. 👍
