### ISSUE TITLE
Initialize database connection?

### ISSUE THREAD

**Issue by Ghostlyr** [Misat11/BedWars#24]
**Describe the bug**
The DatabaseManager is not initialized anywhere and causes NPE when trying get player "database" statistics.

**Server and plugin version**
Spigot version: Paper-636 (MC: 1.13.2)
BedWars version: build from last sources

**Console log:**
```
java.lang.NullPointerException
	at misat11.bw.database.DatabaseManager.getConnection(DatabaseManager.java:43)
	at misat11.bw.statistics.PlayerStatisticManager.initializeDatabase(PlayerStatisticManager.java:64)
	at misat11.bw.statistics.PlayerStatisticManager.initialize(PlayerStatisticManager.java:52)
	at misat11.bw.Main.onEnable(Main.java:308)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
	at java.lang.Thread.run(Thread.java:748)

```

![изображение](https://user-images.githubusercontent.com/8511068/60297487-1d512e80-994a-11e9-9cc5-f8e1955184d6.png)

**Comment by Misat11** [comment]
Fixed dc644e3706cb26e17a5ad32c93e12395f292ea3a
