### ISSUE TITLE
Many bugs.. :(

### ISSUE THREAD

**Issue by Player697** [Misat11/BedWars#6]
There are several problems:
-When the part will end, the player will not be returned to the last position, the inventory will not be restored and if you try to enter again in the game will say that it is in progress, with errors in the console:
[20:41:20 WARN]: [BedWars] Task #9 for BedWars v0.0.7 generated an exception
java.lang.NullPointerException: null
        at misat11.bw.statistics.PlayerStatisticManager.storeYamlStatistic(PlayerStatisticManager.java:221) ~[?:?]
        at misat11.bw.statistics.PlayerStatisticManager.storeStatistic(PlayerStatisticManager.java:215) ~[?:?]
        at misat11.bw.game.Game.leavePlayer(Game.java:467) ~[?:?]
        at misat11.bw.game.GamePlayer.changeGame(GamePlayer.java:24) ~[?:?]
        at misat11.bw.game.Game.run(Game.java:893) ~[?:?]
        at misat11.bw.game.Game$2.run(Game.java:1121) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[20:41:21 WARN]: [BedWars] Task #9 for BedWars v0.0.7 generated an exception
java.lang.NullPointerException: null
        at misat11.bw.statistics.PlayerStatisticManager.storeYamlStatistic(PlayerStatisticManager.java:221) ~[?:?]
        at misat11.bw.statistics.PlayerStatisticManager.storeStatistic(PlayerStatisticManager.java:215) ~[?:?]
        at misat11.bw.game.Game.leavePlayer(Game.java:467) ~[?:?]
        at misat11.bw.game.GamePlayer.changeGame(GamePlayer.java:24) ~[?:?]
        at misat11.bw.game.Game.run(Game.java:893) ~[?:?]
        at misat11.bw.game.Game$2.run(Game.java:1121) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[BW] Game prova is already running! You cannot join to running game!
-When you will be inside the lobby, if you try to leave the lobby, you will not be able to do it and console errors will appear:
[20:46:34 ERROR]: Could not pass event PlayerInteractEvent to BedWars v0.0.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:982) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at misat11.bw.statistics.PlayerStatisticManager.storeYamlStatistic(PlayerStatisticManager.java:221) ~[?:?]
        at misat11.bw.statistics.PlayerStatisticManager.storeStatistic(PlayerStatisticManager.java:215) ~[?:?]
        at misat11.bw.game.Game.leavePlayer(Game.java:467) ~[?:?]
        at misat11.bw.game.GamePlayer.changeGame(GamePlayer.java:24) ~[?:?]
        at misat11.bw.game.Game.leaveFromGame(Game.java:717) ~[?:?]
        at misat11.bw.listener.PlayerListener.onPlayerIteract(PlayerListener.java:413) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        ... 18 more
And for now I have not found any other bugs.

**Comment by Misat11** [comment]
Version with statistics is not correctly working yet because It's not finished yet.

**Comment by Drc-DEV** [comment]
Vault repo is back

**Comment by Misat11** [comment]
fbed103ce45386197e6ad66b8a838f3f2b46411e
